### ISSUE TITLE
Yes/No function not getting right data

### ISSUE THREAD

**Issue by dynodaan** [dynodaan/D6-Bot#2]
Unable to get the wanted Items from the API, don’t know much JSON

#ask the bot for a random yes/no reponse + gif --- NEED TO FIX
def get_yesno_images():
  response = requests.get("https://yesno.wtf/api?ref=apilist.fun")
  json_data = json.loads(response.text)
  yesno_image = str(json_data[0]['answer']) + json_data[0]['image']
  return(yesno_image)

**Comment by rafidini** [comment]
Hi @dynodaan , I can give you a possible answer :

### Explanation
1. What you return by using `requests.get("https://yesno.wtf/api?ref=apilist.fun")` is a `requests.Response`

2. This response contains a `json` method that you can call as follows
```python
response = requests.get("https://yesno.wtf/api?ref=apilist.fun")
json_data = response.json()
# {'answer': 'yes', 'forced': False, 'image': 'https://yesno.wtf/assets/yes/12-e4f57c8f172c51fdd983c2837349f853.gif'}
```

3. If you want to get the `image` key you only have to get the value at the specified key :
```
json_data.get('image')
# OR
json_data['image']
```

### Conclusion
```python
def get_yesno_images():
    response = requests.get("https://yesno.wtf/api?ref=apilist.fun")

    # Try to handle non successful GET request
    if response.status_code != 200:
        return None

    # Get response as a dictionary
    json_data = response.json()

    # Return value @image key
    return json_data.get('image')
```

**Comment by dynodaan** [comment]
Works Great, Thanks!
